### ISSUE TITLE
minor question

### ISSUE THREAD

**Issue by prathamgit** [saadgroup/TurboGenPY#8]
In the line
https://github.com/saadgroup/TurboGenPY/blob/87ebacc354cbf426783e8bf023ea16bba87814c3/example.py#L73
lx = 18*pi/100, and the previous line states L=2*pi/15 for a CBC spectrum. Does that mean the default value of lx is not for the CBC spectrum ?

**Comment by DQuanR2** [comment]
I am not sure I understood your question. The domain size can be changed, but it is recommended to use L=9*2*pi/100. You can find more information in the paper suggested by the authors: "Scalable Tools for Generating Synthetic Isotropic Turbulence with Arbitrary Spectra"

**Comment by prathamgit** [comment]
I see. I was just pointing out that the domain length in comment and the default value being used was different.
